data:
  FUNCTIONS_WORKER_RUNTIME: bm9kZQ==
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9anNpdGVtcztBY2NvdW50S2V5PS94eitzWmJNME53emtjRVJQVDgwVS9zVTlOWWR2VkFpQWUxVk84OUkvdGttdCsvb0hDVmtGL3N3WHpINXFYWEtLUnFXSzNncWx0R2dhZmgxb2hMQTNBPT0=
apiVersion: v1
kind: Secret
metadata:
  name: keda-sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-sample
  labels:
    app: keda-sample
spec:
  selector:
    matchLabels:
      app: keda-sample
  template:
    metadata:
      labels:
        app: keda-sample
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: keda-sample
        image: shankarvrp/keda-sample:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: FuncStorTrig
        envFrom:
        - secretRef:
            name: keda-sample
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-sample
  labels: {}
spec:
  scaleTargetRef:
    name: keda-sample
  triggers:
  - type: azure-queue
    metadata:
      direction: in
      queueName: kedaqueue
      connectionFromEnv: AzureWebJobsStorage
---

